### ISSUE TITLE
Npm dependency not found

### ISSUE THREAD

**Issue by MJE10** [CodinGame/SpringChallenge2022#6]
When running npm install in the src/main/resources/view folder, I get the following error:

System:

OS Name	Microsoft Windows 10 Home
Version	10.0.19043 Build 19043
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	SPECTRE-X360-EL
System Manufacturer	HP
System Model	HP Spectre x360 Convertible 15-eb0xxx
System Type	x64-based PC
System SKU	9GB30UA#ABA
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)

Edit: npm version: 16.13.1

---

Error (more info in attached file):
[2022-04-21T18_16_34_888Z-debug.log](https://github.com/CodinGame/SpringChallenge2022/files/8534086/2022-04-21T18_16_34_888Z-debug.log)

npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://build.codingame.com/nexus/repository/npm-all/xregexp/-/xregexp-4.4.1.tgz
npm ERR! 404 

npm ERR! 404  'xregexp@http://build.codingame.com/nexus/repository/npm-all/xregexp/-/xregexp-4.4.1.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\micha\AppData\Local\npm-cache\_logs\2022-04-21T18_16_34_888Z-debug.log

Process finished with exit code 1

**Comment by CGjupoulton** [comment]
Fixed in https://github.com/CodinGame/SpringChallenge2022/commit/6ab406e3c20128f0d3589435954d5b1f98800d65
